### ISSUE TITLE
Missing file "cairo"

### ISSUE THREAD

**Issue by Matti07** [rckTom/ChuteMaker#1]
Hi Thomas,
when i try to run your example

**python chutemaker.py --grid --panels=12 --seam_allowance=10 --joint_style=miter spherical --diameter=500 --spill_diameter=100 pattern.pdf**

i get the following error:

**File "chutemaker.py", line 1, in <module>
    from ChutePattern import MitreType
  File "/home/[...]/ChuteMaker-master/ChutePattern.py", line 1, in <module>
    import cairo
ImportError: No module named cairo**

The message is correct, i cannot find the mentioned file in "ChuteMaker-master.zip" or elsewhere.
Regards
Matti

**Comment by rckTom** [comment]
Hi Matti, 

chutemaker requires the following dependencies:
- shapely
- pycairo
- numpy
- scipy

Have you installed them on your system? To install them please run:
` python -m pip install scipy numpy pycairo shapely`

If you are having problems running the programm yourself, you can use my hosted version of the program at https://chutemaker.lfence.de
